### PR TITLE
Add documentation for configuring RESTBase API

### PR DESCRIPTION
**Pull request by refeed**
Add "Configure RESTBase API" section in line 50.

### CODE REVIEW

**Comment by gaieges** [comment]
Is there a reason why this hasn't been merged?  Ran into an issue with this setting and couldn't find any documentation around it aside from this PR.

**Comment by refeed** [comment]
ping @gwicke

**Comment by gaieges** [comment]
Why close it @davidbarratt ?

**Comment by davidbarratt** [comment]
@gaieges because the README has been completely rewritten for docker-library/official-images#3281

**Comment by gaieges** [comment]
@davidbarratt i dont see anything about the RESTBase stuff there, did I miss it?

**Comment by davidbarratt** [comment]
@gaieges We don't have an official docker image, so I decided to slim this one down to basically "bare bones" and make it similar to the Drupal & WordPress images. After some discussion on docker-library/official-images#3271 it seemed best that the official image be on the @wikimedia org. Since this repo didn't seem to be maintained anymore (despite my best efforts to reach out to anyone involved) I took over the repo.

Because of this RESTBase is not included in the image. But you should be able to extend this image easiy (especially when docker-library/official-images#3281 is merged).

**Comment by gaieges** [comment]
Understood, I was just trying to make sure you're aware that there isn't
really any good documentation out there on the rest base stuff, aside from
this pr.

**Comment by davidbarratt** [comment]
@gaieges uhh... maybe add it somewhere here? https://www.mediawiki.org/wiki/RESTBase

**Pull request closed without merging**
