### PR TITLE
Add future version

### PR DESCRIPTION
**Pull request by davidbarratt**
Add the future version for testing.

### CODE REVIEW

**Comment by addshore** [comment]
sounds fine

**Comment by magol** [comment]
I like the idea, but then it must be kept in sync with the latest build. 

In order for this idea to work, I think it must be included in the build flow at MediaWiki to update this.

**Comment by davidbarratt** [comment]
Yeah I mean I would prefer if the whole thing was automatted, so maybe we should not add this until the existing versions are automatted.

**Comment by magol** [comment]
@davidbarratt 
After I saw your PR, I actually created an [issue](https://phabricator.wikimedia.org/T197220) on phabricator.wikimedia.org. Hopefully, there is a greater chance that the right people see the sugestion there.

**Pull request closed without merging**
