### PR TITLE
Use PHP 8.0 & 8.1 as the base now that 7.4 is EOL

### PR DESCRIPTION
**Pull request by legoktm**

### CODE REVIEW

**Comment by gesinn-it-gea** [comment]
see https://phabricator.wikimedia.org/T324427#8441788

**Comment by JeroenDeDauw** [comment]
Changing major PHP versions can break things for users of the image. If such changes are made, then I can only recommend people not to use the `mediawiki` image for anything serious. If you pull in `mediawiki:1.35` you do not expect to suddenly get a PHP version that breaks your REL1_35 extensions.

**Comment by gesinn-it-gea** [comment]
@JeroenDeDauw ... I had the same issue and created https://github.com/gesinn-it/docker-mediawiki-base

**Comment by legoktm** [comment]
Sorry for not responding here, I had replied on Phabricator. In short, Docker told us to move off 7.4 (c.f. https://github.com/docker-library/official-images/pull/13622#issuecomment-1332695940). And of course, there's other people complaining that we were using an EOL version of PHP, wanting the upgrade!

Forking is encouraged if you have stricter requirements than what this image can provide.

**Pull request merged**
