### PR TITLE
Add 1.35

### PR DESCRIPTION
**Pull request by Ladsgroup**
It's not officially released yet but having the RC as a docker image
helps us test it easier.

### CODE REVIEW

**Comment by Ladsgroup** [comment]
> This should be generated with `update.sh` now. :)

It doesn't work for RCs, because this bash function filters out anything that has alphabet in it:
```
git ls-remote --tags https://github.com/wikimedia/mediawiki.git \
		| cut -d/ -f3 \
		| grep -viE '[a-z]' \
		| tr -d '^{}' \
		| sort -V \
		| grep -E "^$1" \
		| tail -1
```
let me see if I can fix that.

**Comment by Ladsgroup** [comment]
FWIW, the update.sh didn't make a change.

**Comment by minglecm** [comment]
Hi, is there a schedule for when 1.35 will appear on Dockerhub?  Willing to help if there's a guide/instructions/past example diff somewhere.

**Comment by davidbarratt** [comment]
> Hi, is there a schedule for when 1.35 will appear on Dockerhub? Willing to help if there's a guide/instructions/past example diff somewhere.

There is no schedule. I've been running `./update.sh` but no dice. If you'd like the debug the script to see why it's not picking up the most recent tag on GitHub https://github.com/wikimedia/mediawiki/tags that would be helpful. :)

**Comment by davidbarratt** [comment]
@minglecm I created a task to fix whatever the problem is: https://phabricator.wikimedia.org/T263948

**Pull request merged**
