### PR TITLE
Update base image

### PR DESCRIPTION
**Pull request by jahanzaibasharat**
it's not building. i get this error:
E: Package 'libpng12-dev' has no installation candidate
should change base image to php:7.1-apache-jessie or php:7.1-apache-stretch (accordingly)

### CODE REVIEW

**Comment by davidbarratt** [comment]
I'm going to decline this because `7.1-apache` is the same thing as `7.1-apache-stretch`. We should fix whatever the problem is with stretch.

**Comment by davidbarratt** [comment]
I did a pull on the base image:
```
docker pull php:7.1-apache
```
and then a build:
```
docker build .
```
and the build was successful. 

@jahanzaibasharat Can you provide reproduction steps?

**Comment by jahanzaibasharat** [comment]
This is the error i get:

`Digest: sha256:6e2bb50bd83d31ae165f86db4d7c59a43ff32a1a492b0f6f8135cd51e0437fa7
Status: Downloaded newer image for mediawiki:1.30.0
 ---> 0447a27d080f
Step 2/73 : RUN apt-get update && apt-get install -y apt-utils libpng12-dev netcat wget unzip vim
 ---> Running in 389d57343d99
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:5 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [442 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [12.1 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [9530 kB]
Fetched 10.3 MB in 10s (968 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libpng12-dev' has no installation candidate
The command '/bin/sh -c apt-get update && apt-get install -y apt-utils libpng12-dev netcat wget unzip vim' returned a non-zero code: 100
ERROR: Job failed: exit code 100`

**Comment by davidbarratt** [comment]
I can't find this line anywhere in the repo:`libpng12-dev` and I know we are not installing `vim`.

Are you certain you're building from the latest `master` branch (from github)?

**Comment by jahanzaibasharat** [comment]
libpng12-dev is a dependency of zlib1g-dev.
it was used in debian:jessie, from debian:scratch the dependency for zlib1g-dev is libpng-dev.
it seems like it's loading the wrong dependecy. if you see the log i pasted above it's using debian:stretch but it is still searching for libpng12-dev...

I am trying to understand how to overcome this problem. 
I am using mediawiki:1.30.0 from dockerhub, not using it directly but as a base (FROM mediawiki:1.30.0).

**Comment by davidbarratt** [comment]
Can you provide a url to the Dockerfile you're attempting to build?

**Comment by tianon** [comment]
Replace `libpng12-dev` with `libpng-dev` in your `Dockerfile` and it should build again.

**Comment by jahanzaibasharat** [comment]
solved. thankyou.

**Pull request closed without merging**
