### PR TITLE
2024 12 23 mediawiki updates

### PR DESCRIPTION
**Pull request by christian-heusel**
- **remove the EOL MediaWiki 1.41**
- **Add missing gpg identity to the templates**
- **Add MediaWiki 1.43.0**

### CODE REVIEW

**Comment by christian-heusel** [comment]
Requesting explicit review because of the GPG changes here 😊

**Comment by Richard-Degenne** [comment]
Hello!

I noticed that the 1.43 image is not available yet on DockerHub. Do you have an idea on when it will be pushed?

**Comment by christian-heusel** [comment]
Hey @Richard-Degenne we're still waiting on review & merge on this PR from the Docker Inc. team: https://github.com/docker-library/official-images/pull/18170

I guess people are on vacation 😅 For the time being you can just clone this repo and build the repo with `docker build` yourself 😄

**Comment by Richard-Degenne** [comment]
Oh, right, didn't see the mentioned PR right away! Thanks!

**Pull request merged**
