### PR TITLE
Upgrade MediaWiki to 1.29.1

### PR DESCRIPTION
**Pull request by davidbarratt**

### CODE REVIEW

**Comment by legoktm** [comment]
Is this something that will need to be done manually every time there's a new MediaWiki release? (Can we automate it somehow?)

**Comment by tianon** [comment]
In docker-library-maintained repositories, we usually create an `update.sh` script which does version bumps (like https://github.com/docker-library/redis/blob/ebde981d2737c5a618481f766d253afff13aeb9f/update.sh, for example), and then we've got @docker-library-bot running in Jenkins to automate actually making the commits (https://github.com/docker-library/redis/commit/ebde981d2737c5a618481f766d253afff13aeb9f).  That leaves a PR updating `library/FOO` as the only manual piece, which we also usually create a script for (https://github.com/docker-library/redis/blob/ebde981d2737c5a618481f766d253afff13aeb9f/generate-stackbrew-library.sh), and then do update PRs in bulk (https://github.com/docker-library/official-images/pull/3253).

**Comment by tianon** [comment]
(And I'd be happy to help write any of that scaffolding if it's desirable
-- including the Jenkins bits. :+1:)

**Comment by legoktm** [comment]
@davidbarratt and @addshore are the main leads of this project, but I'd favor automatic updates, especially for security releases.


My bash is pretty poor so I'm not sure how to do the file editing stuff, but here's what I put together to get the latest MediaWiki releases and their sha512s. Is this useful as a starting point?
```bash
#!/bin/bash
set -eu

expand_template () {
	template=$1
	echo $template
	VALUE=`curl "https://www.mediawiki.org/w/api.php?action=expandtemplates&text=\{\{${template}\}\}&format=json&formatversion=2&prop=wikitext" | jq '.expandtemplates.wikitext' | sed 's/"//g'`
}

expand_template MW_stable_release_number
STABLE=$VALUE
expand_template MW_stable_branch_number
STABLE_BRANCH=$VALUE
expand_template MW_legacy_release_number
LEGACY=$VALUE
expand_template MW_legacy_branch_number
LEGACY_BRANCH=$VALUE
expand_template MW_legacy_lts_release_number
LTS=$VALUE
expand_template MW_legacy_lts_branch_number
LTS_BRANCH=$VALUE

get_sha512 () {
	branch=$1
	version=$2
	# TODO: gpg verify tarball?
	VALUE=`curl "https://releases.wikimedia.org/mediawiki/${branch}/mediawiki-${version}.tar.gz"  | sha512sum | sed 's/\-//'`
}


get_sha512 $STABLE_BRANCH $STABLE
STABLE_SHA=$VALUE
get_sha512 $LEGACY_BRANCH $LEGACY
$LEGACY_SHA=$VALUE
get_sha512 $LTS_BRANCH $LTS
$LTS_SHA=$VALUE
```

**Comment by davidbarratt** [comment]
@legoktm what would kick this off?

**Comment by legoktm** [comment]
I think @tianon was thinking to use @docker-library-bot which gets triggers from a jenkins instance?

**Pull request merged**
