### PR TITLE
Add bug tracker link

### PR DESCRIPTION
**Pull request by sau226**
Requested by @addshore in T179660.

### CODE REVIEW

**Comment by davidbarratt** [comment]
oh.. I see docker-library/docs#1165 umm... I don't think we should change the README here since it's generated file.... but maybe it's ok to do that? we'd have to check with the folks at @docker-library since they review every change.

**Comment by tianon** [comment]
We don't do any review on this `README` file -- it's ignored entirely, so can say whatever is most useful for the project. :+1:

(For the repos that live under https://github.com/docker-library, we use https://github.com/docker-library/docs/blob/7bbcc0eecbf52620bfc4ba4493fc4a149b7ad27e/generate-repo-stub-readme.sh to generate their `README.md` contents just so that they're all consistent.)

**Comment by sau226** [comment]
Can someone with merge access schedule/merge this please? Thanks

**Comment by sau226** [comment]
That was fast

**Pull request merged**
